behaviors:
  CarParking:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 32768
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 2
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 50000000
    time_horizon: 256
    summary_freq: 200000
    checkpoint_interval: 500000
    keep_checkpoints: 200
environment_parameters:
  initial_position:
    curriculum:
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: CarParking
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 3
        value: -10.0
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: CarParking
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 3
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: -15.0
            max_value: -10.0
      - name: Lesson3
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: -25.0
            max_value: -10.0
  initial_rotation:
    curriculum:
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: CarParking
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 3
        value: 0.0
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: CarParking
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 3
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: -20.0
            max_value: 20.0
      - name: Lesson3
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: -45.0
            max_value: 45.0
  number_of_full_spots:
    curriculum:
    - name: Lesson1
      completion_criteria:
        measure: reward
        behavior: CarParking
        signal_smoothing: true
        min_lesson_length: 500
        threshold: 3.2
      value: 0
    - name: Lesson2
      completion_criteria:
        measure: reward
        behavior: CarParking
        signal_smoothing: true
        min_lesson_length: 500
        threshold: 3.3
      value: 2
    - name: Lesson3
      completion_criteria:
        measure: reward
        behavior: CarParking
        signal_smoothing: true
        min_lesson_length: 1000
        threshold: 3.4
      value: 5
    - name: Lesson4
      completion_criteria:
        measure: reward
        behavior: CarParking
        signal_smoothing: true
        min_lesson_length: 2000
        threshold: 3.5
      value: 8
    - name: Lesson5
      value: 13